[core]
search_api_key=tvly-***

[llm]
api_key=sk-ant-api03-***
provider=anthropic
model=anthropic/claude-sonnet-4-20250514
num_retries=3

[agent]
enable_browsing = true

enable_llm_editor = false

enable_editor = true

enable_jupyter = true

enable_cmd = true

enable_think = true

enable_finish = true

[sandbox]
platform=linux/amd64
