[core]
search_api_key = "tvly-***"
platform = "linux/amd64" # Can be linux/amd64 or linux/arm64

# Enable the browser environment
enable_browser = true

[llm]
api_key = "sk-proj-***"
# API base URL (For Headless / CLI only -  In Web this is overridden by Session Init)
#base_url = ""
provider = "openai" # Can be openai, anthropic, deepseek, openrouter
# Model to use. (For Headless / CLI only -  In Web this is overridden by Session Init)
model = "openai/o3"
reasoning_effort = "high"

[agent]

# Whether the browsing tool is enabled
# Note: when this is set to true, enable_browser in the core config must also be true
enable_browsing = true
