[core]
search_api_key=tvly-I***
reasoning_effort=high

[llm]
api_key=sk-or-v1-***
provider=openrouter
model=openrouter/google/gemini-2.5-pro
num_retries=3

[agent]
enable_browsing = true

enable_llm_editor = false

enable_editor = true

enable_jupyter = true

enable_cmd = true

enable_think = true

enable_finish = true

[sandbox]
platform=linux/amd64

